language: node_js
node_js:
- '10'
branchs:
  only:
  - master
install:
- npm install
addons:
  ssh_known_hosts: 188.131.206.251
after_success:
- ssh root@ydserver "./travis_build"
before_install:
- openssl aes-256-cbc -K $encrypted_b5ed83347018_key -iv $encrypted_b5ed83347018_iv
  -in ./.travis/jhx_rsa.enc -out ~/.ssh/jhx_rsa -d
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm test
after_scripts:
- scp -o StrictHostKeyChecking=no app.js root@188.131.206.251:/home
deploy:
  skip_cleanup: true
