language: node_js
node_js:
- '10'
branchs:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_cac45ecce511_key -iv $encrypted_cac45ecce511_iv
  -in jhx_rsa.enc -out ~\/.ssh/jhx_rsa -d
  - chmod 600 ~/.ssh/jhx_rsa
install:
- npm install
script:
- npm test
addons:
  ssh_known_hosts: 188.131.206.251

after_success:
  - ssh root@188.131.206.251 "./travis_build"
